language: node_js
node_js:
- '0.12'
- '4.0'
- iojs
before_script:
- npm install -g bower
branches:
  only:
    - master
env:
  global:
  - secure: ynSpcXOzvtEZbr7hS10QEpXPapzw+VZful8nqlaLYl6c1y+ch89mYbeJxtNCCUlweMGiUIShqfAJWq11vV8l0WT1IeK2i036MfipRG2eg2mwfDZ9ahms1zbMiM1gq8VEpoSB26rrNQS8J5nnHUBA0rnG0+39np08D1xeSRDaRMOwER4o29EJT16BZReT22T5+y+iHWz5FY2ulP3nAvkDGHffOiaKvLNDSV5W8AMpNC6YmjBa3FzSg7/1C0xA9exlSNM96ps/s59erfbW9UXyGdTfKiQz5ZQWIoz4ivBBv5PQiy0B8glnL9RlL8TSLXys7yl/fBGWBfjC1NYMR5fWPBrWamqA6huFVc08nXLtEMBPmZryQlj6P8onx/6JuoHBR76kI3dN7aaDHOIbVEmfaRKAQlAZDz6LBJhzqDQGQTQIBy30neMCAqObhua4X8OFGYRCkiBVAiHQR9bLtCC1gtz6q34lHdS4Cbiir0oMIU4/oiaJAzs7AB9pZwhLSLnU9AozVSHe0r1+I1+mges6uzxK7xy3kGyyaqq9WrQ7jujop20HEpJtgqAsDFRfaDEUBAnOxJPXwkD+/9h+sByJbPCIQ0nUBR19s8/7ZWZVes3ME2yNiwwkjvWnoTrt/68+1jhDIjVKdTPgdvP76o3bI0ohaG71Xay+7PMrTMv6WJo=
