# Site settings
title: Boneyard Documentation
email: 3dimentionar@gmail.com
description: Architectural Toolkit for Web Development
baseurl: ""
url: "http://boneyard.nahuel.io/" # the base hostname & protocol for your site
twitter_username: patokuakman
github_username:  nahuelio/boneyard

# Build settings
markdown: kramdown

sass:
    style: compressed

include:
  - .nojekyll

# Jekyll doesn't support globs?
exclude:
  - bower.json
  - libs/jquery/src
  - libs/jquery/dist/jquery.js
  - libs/jquery/bower.json
  - libs/jquery/MIT-LICENSE.txt
  - libs/bootstrap/dist/js/bootstrap.js
  - libs/bootstrap/dist/js/npm.js
  - libs/bootstrap/fonts
  - libs/bootstrap/grunt
  - libs/bootstrap/js
  - libs/bootstrap/less
  - libs/bootstrap/bower.json
  - libs/bootstrap/Gruntfile.js
  - libs/bootstrap/LICENSE
  - libs/bootstrap/package.js
  - libs/bootstrap/package.json
  - libs/bootstrap/README.md
  - libs/fontawesome/less
  - libs/fontawesome/scss
  - libs/fontawesome/.bower.json
  - libs/fontawesome/.gitignore
  - libs/fontawesome/.npmignore
  - libs/fontawesome/bower.json
  - libs/fontawesome/HELP-US-OUT.txt
