# Site settings
title: Boneyard Documentation
email: 3dimentionar@gmail.com
description: Architectural Toolkit for Web Development
baseurl: "/boneyard"
url: "http://3dimention.github.io/boneyard" # the base hostname & protocol for your site
twitter_username: patokuakman
github_username:  3dimention/boneyard

# Build settings
markdown: kramdown

sass:
    style: compressed

# Jekyll doesn't support globs?
include:
  - .nojekyll

exclude:
  - bower.json
  - libs/jquery/src
  - libs/jquery/dist/jquery.js
  - libs/jquery/bower.json
  - libs/jquery/MIT-LICENSE.txt
  - libs/bootstrap/dist/js/bootstrap.js
  - libs/bootstrap/dist/js/npm.js
  - libs/bootstrap/fonts
  - libs/bootstrap/grunt
  - libs/bootstrap/js
  - libs/bootstrap/less
  - libs/bootstrap/bower.json
  - libs/bootstrap/Gruntfile.js
  - libs/bootstrap/LICENSE
  - libs/bootstrap/package.js
  - libs/bootstrap/package.json
  - libs/bootstrap/README.md
